---
title: "About"
---

In greater detail, I am a student who enjoys learning new math and coding sometimes. Public health is interesting, I think it is good to think about research in the context of things that matter a great deal to the general population. I think researchers and scientists tend to only focus on their research/science, and neglect other factors that are also important to consider. For example, I hear a lot of people say that policymakers should just do what science tells them to do, but there are several other things to keep in mind. Feasibility, budget, ethics, and much more are also important.

I am currently applying to graduate schools for PhD and also industry jobs, because I would like to have options of what to do next after undergrad. I am interested primarily in the health sector because I think it could be fulfilling, and am looking for data science jobs because that's where most of my skills lie. I lack in biology/chemistry knowledge (definitely in terms of coursework) so I am hoping to get hired based on technological skillset.
